name: esdm
description: Biro SDM Polda Metro Jaya

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0
  flutter_rounded_date_picker: 1.0.0
  flutter_staggered_grid_view: 0.3.0
  flutter_launcher_icons: "^0.7.3"
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_slider: ^1.4.0
  google_maps_flutter: ^0.5.24+1
  rflutter_alert: ^1.0.3
  pref_dessert: ^0.5.1
  shared_preferences: ^0.5.4+3
  flutter_plugin_pdf_viewer: 1.0.7
  flutter_pubnub: ^0.2.0
  dropdown_formfield: ^0.1.1
  flutter_webview_plugin: 0.3.10+1
  webview_flutter: ^0.3.19+9
  dotted_border: ^1.0.5
  flutter_svg: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: "launcher_icon"
  image_path_ios: "lib/assets/launcher/sdm.png"
  image_path_android: "lib/assets/launcher/sdm.png"
  adaptive_icon_background: "lib/assets/launcher/sdm.png"
  adaptive_icon_foreground: "lib/assets/launcher/sdm.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - lib/assets/img/sdmpolri.jpeg
    - lib/assets/img/metrojaya.jpeg
    - lib/assets/img/pmj.png
    - lib/assets/img/naik_pangkat.png
    - lib/assets/img/mutasi.png
    - lib/assets/img/emc2.jpeg
    - lib/assets/img/emc2.png
    - lib/assets/img/disposisi.png
    - lib/assets/img/pangkat.png
    - lib/assets/img/tryout.png
    - lib/assets/img/catpers.png
    - lib/assets/img/cadet.png
    - lib/assets/img/konsultasi.png
    - lib/assets/file/sample.pdf
    - lib/assets/fonts/sit-up.svg
    - lib/assets/fonts/push-up.svg
    - lib/assets/fonts/swimming-pool.svg
    - lib/assets/fonts/training.svg
    - lib/assets/fonts/tracking.svg
    - lib/assets/fonts/track.svg
    - lib/assets/fonts/hospital.svg

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
